In [1]:

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
                     ("that was the best meal i've ever had in my life", "positive"),
                     ("i feel so grateful for everything i have in my life", "positive"),
                     ("i received a promotion at work and i couldn't be happier", "positive"),
                     ("watching a beautiful sunset always fills me with joy", "positive"),
                     ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                     ("i am so proud of my daughter for graduating with honors", "positive"),
                     ("listening to my favorite music always puts me in a good mood", "positive"),
                     ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                     ("i am excited to go on vacation next week", "positive"),
                     ("i feel so overwhelmed with work and responsibilities", "negative"),
                     ("the traffic during my commute is always so frustrating", "negative"),
                     ("i received a parking ticket and it ruined my day", "negative"),
                     ("i got into an argument with my partner and we're not speaking", "negative"),
                     ("i have a headache and i feel terrible", "negative"),
                     ("i received a rejection letter for the job i really wanted", "negative"),
                     ("my car broke down and it's going to be expensive to fix", "negative"),
                     ("i'm feeling sad because i miss my friends who live far away", "negative"),
                     ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                     ("i'm disappointed because my team lost the game", "negative")
                    ],columns=['Text','Sentiment'])

In [3]:
data.head()

                                                Text Sentiment
0    i love spending time with my friends and family  positive
1    that was the best meal i've ever had in my life  positive
2  i feel so grateful for everything i have in my...  positive
3  i received a promotion at work and i couldn't ...  positive
4  watching a beautiful sunset always fills me wi...  positive

In [4]:
data = data.sample(frac=1).reset_index(drop=True)

In [5]:
data.head(10)

                                                Text Sentiment
0     i'm disappointed because my team lost the game  negative
1  listening to my favorite music always puts me ...  positive
2  i love the feeling of accomplishment after com...  positive
3  i'm frustrated because i can't seem to make pr...  negative
4  i received a rejection letter for the job i re...  negative
5  my car broke down and it's going to be expensi...  negative
6              i have a headache and i feel terrible  negative
7  i feel so overwhelmed with work and responsibi...  negative
8    that was the best meal i've ever had in my life  positive
9    i love spending time with my friends and family  positive

In [6]:
X = data['Text']
y = data['Sentiment']

In [7]:
print(X[:5])

0       i'm disappointed because my team lost the game
1    listening to my favorite music always puts me ...
2    i love the feeling of accomplishment after com...
3    i'm frustrated because i can't seem to make pr...
4    i received a rejection letter for the job i re...
Name: Text, dtype: object

In [8]:
# text vectorization to bow - CountVectorizer
countvec = CountVectorizer()
countvec_fit = countvec.fit_transform(X)
bag_of_words = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out())

In [9]:
bag_of_words

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
8,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
9,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
17,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, y, test_size=0.3, random_state = 7) # split into train and test data

In [11]:
lr = LogisticRegression(random_state=1).fit(X_train, y_train)

In [12]:
y_pred_lr = lr.predict(X_test)

In [13]:
accuracy_score(y_pred_lr, y_test)

0.5

In [14]:
y_pred_lr

array(['positive', 'positive', 'negative', 'negative', 'negative',
       'negative'], dtype=object)

In [15]:
y_test

1     positive
17    negative
2     positive
5     negative
11    positive
0     negative
Name: Sentiment, dtype: object

In [16]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB().fit(X_train, y_train)

In [17]:
y_pred_nb = nb.predict(X_test)
accuracy_score(y_pred_nb, y_test)

0.6666666666666666

In [18]:
print(classification_report(y_test, y_pred_nb, zero_division=0))

              precision    recall  f1-score   support

    negative       0.67      0.67      0.67         3
    positive       0.67      0.67      0.67         3

    accuracy                           0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6

In [19]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
svm = SGDClassifier().fit(X_train, y_train)
# possible hyper params, loss function, regularization
y_pred_svm = svm.predict(X_test)
accuracy_score(y_pred_svm, y_test)

0.5

In [20]:
print(classification_report(y_test, y_pred_svm, zero_division=0))

              precision    recall  f1-score   support

    negative       0.50      0.67      0.57         3
    positive       0.50      0.33      0.40         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6